
consul_dir: '/usr/local/sbin'
consul_conf_dir: '/etc/consul.d'
consul_data_dir: '/var/consul'
consul_log_dir: '/var/log/consul'
consul_ui_dir: '/srv/consul_ui'

consul_tmp_pkg: "/tmp/consul.zip"

consul_version: "0.4.1"
consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"

consul_ui_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_web_ui.zip"


consul_user: consul
consul_group: consul
consul_log_level: info
consul_bootstrap_expect: 2
consul_supervisor_enabled: false
consul_supervisord_config_dir: /etc/supervisor.d
consul_join: []

consul_server_pip_dependencies:
  - python-consul
  - pyhcl
  - httplib2
  - raven
  - pytz
  - tzlocal

consul_root_cert_installed: false

# make sure these get interpreted as strings not booleans
json_true: 'true'
json_false: 'false'

# config values from http://www.consul.io/docs/agent/options.html

consul_datacenter: dc1

consul_interface: 0.0.0.0
consul_client_address: '{{consul_interface}}'
consul_advertise_address: '{{consul_interface}}'
consul_bind_address: '{{consul_interface}}'

consul_acl_enabled: true
consul_acl_datacenter: '{{consul_datacenter}}'
consul_acl_default_policy: 'allow'
consul_acl_down_policy: 'extend-cache'

consul_acl_master_token: 4791402A-D875-4C18-8316-E652DBA53B18
consul_acl_token: C818728E-5D0F-4E97-8CDA-C4E4F9518744
consul_acl_ttl: 30s

consul_dns_address: '{{consul_client_address}}'
consul_http_address: '{{consul_client_address}}'
consul_rpc_address: '{{consul_client_address}}'

consul_dns_port: 8600
consul_http_port: 8500
consul_rpc_port: 8400
consul_serf_lan_port: 8301
consul_serf_wan_port: 8302
consul_server_port: 8300

consul_verify_incoming: '{{json_false}}'
consul_verify_outgoing: '{{json_false}}'

consul_cert_file: '{{consul_dir}}/conf.d/consul.crt'
consul_key_file: '{{consul_dir}}/conf.d/consul.key'

consul_check_update_interval: 5m

consul_disable_anonymous_signature: '{{json_false}}'
consul_disable_remote_exec: '{{json_false}}'
consul_disable_update_check: '{{json_false}}'

consul_dns_enabled: true
consul_dns_allow_stale: '{{json_false}}'
consul_dns_max_stale: 5s
consul_dns_node_ttl: 0s
consul_dns_enable_truncate: '{{json_false}}'
consul_dns_domain: "consul."

consul_enable_debug: '{{json_false}}'

consul_enable_syslog: '{{json_true}}'

consul_encrypt_enabled: '{{json_false}}'
consul_encrypt_key: WemSfNqARydofnJFh5bDEA==

consul_leave_on_terminate: '{{json_true}}'

consul_rejoin_after_leave: '{{json_true}}'

consul_retry_join: '{{consul_join}}'

consul_retry_interval: 30s

consul_retry_max: 10

consul_server: false

consul_server_name: '{{ node_name }}'
consul_node_name: '{{ node_name}}'

consul_skip_leave_on_interrupt: '{{json_false}}'

consul_syslog_facility: LOCAL0
